version: '3.2'

services:

  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    ports:
      - 20080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated